/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellRouteImport } from './routes/upsell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as MissedCallsRouteImport } from './routes/missed-calls'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FollowupRouteImport } from './routes/followup'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorsOperatorIdRouteImport } from './routes/operators.$operatorId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ApiTagClientsRouteImport } from './routes/api/tag-clients'
import { Route as ApiSofiaRouteImport } from './routes/api/sofia'
import { Route as ApiReminderRespondRouteImport } from './routes/api/reminder-respond'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const UpsellRoute = UpsellRouteImport.update({
  id: '/upsell',
  path: '/upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const MissedCallsRoute = MissedCallsRouteImport.update({
  id: '/missed-calls',
  path: '/missed-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupRoute = FollowupRouteImport.update({
  id: '/followup',
  path: '/followup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsOperatorIdRoute = OperatorsOperatorIdRouteImport.update({
  id: '/$operatorId',
  path: '/$operatorId',
  getParentRoute: () => OperatorsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ApiTagClientsRoute = ApiTagClientsRouteImport.update({
  id: '/api/tag-clients',
  path: '/api/tag-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSofiaRoute = ApiSofiaRouteImport.update({
  id: '/api/sofia',
  path: '/api/sofia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReminderRespondRoute = ApiReminderRespondRouteImport.update({
  id: '/api/reminder-respond',
  path: '/api/reminder-respond',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/followup': typeof FollowupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/missed-calls': typeof MissedCallsRoute
  '/operators': typeof OperatorsRouteWithChildren
  '/reception': typeof ReceptionRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/upsell': typeof UpsellRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reminder-respond': typeof ApiReminderRespondRoute
  '/api/sofia': typeof ApiSofiaRoute
  '/api/tag-clients': typeof ApiTagClientsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/followup': typeof FollowupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/missed-calls': typeof MissedCallsRoute
  '/operators': typeof OperatorsRouteWithChildren
  '/reception': typeof ReceptionRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/upsell': typeof UpsellRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reminder-respond': typeof ApiReminderRespondRoute
  '/api/sofia': typeof ApiSofiaRoute
  '/api/tag-clients': typeof ApiTagClientsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/clients': typeof ClientsRouteWithChildren
  '/followup': typeof FollowupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/missed-calls': typeof MissedCallsRoute
  '/operators': typeof OperatorsRouteWithChildren
  '/reception': typeof ReceptionRoute
  '/reminders': typeof RemindersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/upsell': typeof UpsellRoute
  '/api/chat': typeof ApiChatRoute
  '/api/reminder-respond': typeof ApiReminderRespondRoute
  '/api/sofia': typeof ApiSofiaRoute
  '/api/tag-clients': typeof ApiTagClientsRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/operators/$operatorId': typeof OperatorsOperatorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/chat'
    | '/clients'
    | '/followup'
    | '/forgot-password'
    | '/login'
    | '/loyalty'
    | '/missed-calls'
    | '/operators'
    | '/reception'
    | '/reminders'
    | '/reset-password'
    | '/settings'
    | '/upsell'
    | '/api/chat'
    | '/api/reminder-respond'
    | '/api/sofia'
    | '/api/tag-clients'
    | '/clients/$clientId'
    | '/operators/$operatorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/chat'
    | '/clients'
    | '/followup'
    | '/forgot-password'
    | '/login'
    | '/loyalty'
    | '/missed-calls'
    | '/operators'
    | '/reception'
    | '/reminders'
    | '/reset-password'
    | '/settings'
    | '/upsell'
    | '/api/chat'
    | '/api/reminder-respond'
    | '/api/sofia'
    | '/api/tag-clients'
    | '/clients/$clientId'
    | '/operators/$operatorId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/bookings'
    | '/chat'
    | '/clients'
    | '/followup'
    | '/forgot-password'
    | '/login'
    | '/loyalty'
    | '/missed-calls'
    | '/operators'
    | '/reception'
    | '/reminders'
    | '/reset-password'
    | '/settings'
    | '/upsell'
    | '/api/chat'
    | '/api/reminder-respond'
    | '/api/sofia'
    | '/api/tag-clients'
    | '/clients/$clientId'
    | '/operators/$operatorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  FollowupRoute: typeof FollowupRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  MissedCallsRoute: typeof MissedCallsRoute
  OperatorsRoute: typeof OperatorsRouteWithChildren
  ReceptionRoute: typeof ReceptionRoute
  RemindersRoute: typeof RemindersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  UpsellRoute: typeof UpsellRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiReminderRespondRoute: typeof ApiReminderRespondRoute
  ApiSofiaRoute: typeof ApiSofiaRoute
  ApiTagClientsRoute: typeof ApiTagClientsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsell': {
      id: '/upsell'
      path: '/upsell'
      fullPath: '/upsell'
      preLoaderRoute: typeof UpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missed-calls': {
      id: '/missed-calls'
      path: '/missed-calls'
      fullPath: '/missed-calls'
      preLoaderRoute: typeof MissedCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followup': {
      id: '/followup'
      path: '/followup'
      fullPath: '/followup'
      preLoaderRoute: typeof FollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$operatorId': {
      id: '/operators/$operatorId'
      path: '/$operatorId'
      fullPath: '/operators/$operatorId'
      preLoaderRoute: typeof OperatorsOperatorIdRouteImport
      parentRoute: typeof OperatorsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/api/tag-clients': {
      id: '/api/tag-clients'
      path: '/api/tag-clients'
      fullPath: '/api/tag-clients'
      preLoaderRoute: typeof ApiTagClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sofia': {
      id: '/api/sofia'
      path: '/api/sofia'
      fullPath: '/api/sofia'
      preLoaderRoute: typeof ApiSofiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminder-respond': {
      id: '/api/reminder-respond'
      path: '/api/reminder-respond'
      fullPath: '/api/reminder-respond'
      preLoaderRoute: typeof ApiReminderRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface OperatorsRouteChildren {
  OperatorsOperatorIdRoute: typeof OperatorsOperatorIdRoute
}

const OperatorsRouteChildren: OperatorsRouteChildren = {
  OperatorsOperatorIdRoute: OperatorsOperatorIdRoute,
}

const OperatorsRouteWithChildren = OperatorsRoute._addFileChildren(
  OperatorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRoute,
  ClientsRoute: ClientsRouteWithChildren,
  FollowupRoute: FollowupRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  MissedCallsRoute: MissedCallsRoute,
  OperatorsRoute: OperatorsRouteWithChildren,
  ReceptionRoute: ReceptionRoute,
  RemindersRoute: RemindersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  UpsellRoute: UpsellRoute,
  ApiChatRoute: ApiChatRoute,
  ApiReminderRespondRoute: ApiReminderRespondRoute,
  ApiSofiaRoute: ApiSofiaRoute,
  ApiTagClientsRoute: ApiTagClientsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
